#
# TABLE STRUCTURE FOR: posts
#

DROP TABLE IF EXISTS `posts`;

CREATE TABLE `posts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `community_id` int(10) unsigned DEFAULT NULL,
  `head` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `body` text COLLATE utf8_unicode_ci NOT NULL,
  `media_id` int(10) unsigned DEFAULT NULL,
  `is_public` tinyint(1) DEFAULT 1,
  `is_archived` tinyint(1) DEFAULT 0,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (1, 46, 5, 'Enim sed aut tempore ut. Distinctio laborum quas qui.', 'Aliquid a id est. Molestiae modi sed magnam eius consequuntur nihil. Sint quo voluptatem est voluptatem ut.', 75, 0, 0, '1995-01-12 12:18:19', '1973-12-25 23:09:33');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (2, 37, 20, 'Quibusdam sequi repellendus totam expedita.', 'Nulla facere eum in. Eum non sit quibusdam voluptatum architecto itaque. Molestiae nemo sed ipsum. Harum voluptas qui consequatur. Ipsa non qui sunt beatae est non id.', 92, 1, 0, '1978-10-26 18:26:21', '2005-11-19 09:55:13');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (3, 47, 14, 'Et recusandae rerum accusamus. Assumenda libero maxime qui culpa.', 'Unde id est reprehenderit dignissimos perferendis cumque et eos. Dolor omnis sit deserunt ipsum. Pariatur omnis quis ratione rerum placeat.', 22, 0, 0, '1987-12-27 22:35:05', '2006-01-09 23:11:38');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (4, 91, 12, 'Nihil corrupti voluptas ex voluptatem dolores qui.', 'Incidunt aliquam nam architecto odit. In quo porro repellendus est eum.', 77, 0, 1, '1976-10-20 00:07:14', '2008-04-25 08:49:55');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (5, 23, 16, 'Porro est suscipit laborum possimus aut ullam.', 'Provident enim hic enim velit expedita quis porro. Dolorem vel nemo consequatur eaque quibusdam. Et ad sed et quam molestiae. Nesciunt odit dolorum dolorum temporibus laborum aut officia.', 39, 0, 1, '1981-08-10 23:13:48', '1999-03-09 00:49:50');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (6, 91, 4, 'Quibusdam minus sit corrupti enim.', 'Perspiciatis maxime mollitia delectus laboriosam aut sed qui. Et nihil aut dolorem. Culpa et vel nulla numquam saepe nulla. Excepturi in itaque earum illo adipisci.', 40, 0, 1, '2004-10-09 02:54:58', '1990-12-16 03:49:06');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (7, 4, 19, 'Nisi qui nobis tempora perferendis veritatis quia distinctio veniam.', 'Consequatur perspiciatis cumque nulla alias. Illo commodi voluptas fuga distinctio cumque ad ut. Facilis dolorem dolor eos enim perferendis labore voluptate.', 49, 1, 0, '2012-03-28 02:04:21', '1988-04-07 06:29:02');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (8, 93, 1, 'Repellat voluptatem saepe sit necessitatibus atque tempore quis vel.', 'Culpa ipsum earum amet est qui. Iusto quod sed ea officia. Nisi animi iure hic quis omnis provident nostrum. Fuga voluptatum rerum odit quia qui.', 22, 1, 1, '1996-08-16 22:37:11', '2004-10-05 09:38:02');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (9, 43, 14, 'Tenetur et deleniti impedit aut ipsum minima.', 'Qui dignissimos animi mollitia odio. Quia expedita saepe delectus ipsa aut quisquam. Nulla harum laboriosam consequatur a culpa laborum.', 61, 1, 0, '1972-10-16 14:29:36', '2012-06-03 13:47:09');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (10, 23, 12, 'Beatae ipsum perferendis molestias omnis quia aut inventore.', 'Quo dolore aliquam ea. Fuga a cupiditate vitae optio porro beatae. Qui et nulla in quidem quo numquam. Aut ipsum eveniet est quod vitae rerum.', 85, 1, 0, '1999-07-24 21:06:28', '1975-10-11 17:29:39');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (11, 12, 7, 'In blanditiis est hic consequatur asperiores minima nisi.', 'Iure non modi soluta quo rem officia odio. Autem non quae debitis cum dolores vel. Quis possimus labore enim sed dolor laboriosam maiores.', 71, 0, 0, '2008-08-23 09:23:22', '2019-06-05 20:28:13');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (12, 45, 10, 'Asperiores qui assumenda est quis.', 'Distinctio ratione sit similique rem esse cupiditate. Ullam architecto minus omnis quia. Ut numquam qui rem magni aperiam natus.', 32, 0, 0, '2016-12-14 08:06:18', '2000-07-12 17:05:19');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (13, 22, 14, 'Voluptas id voluptatem et voluptatem ratione saepe ipsum.', 'Assumenda non nihil qui quisquam sapiente a provident. Asperiores aut qui et et. Et animi consectetur quidem exercitationem aut. Rerum consequatur aut in sed dolore fugiat autem maxime.', 21, 0, 0, '1996-02-11 21:18:58', '1978-05-22 11:57:01');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (14, 30, 10, 'Laborum quis earum ratione maxime nemo.', 'Est quo iusto magnam sed exercitationem. Rem fugiat quis amet assumenda exercitationem nihil. Ut ad debitis modi sed deserunt cumque nostrum. Et excepturi et quis nam explicabo ut magni distinctio.', 18, 1, 0, '1981-02-15 07:49:23', '2014-05-06 09:20:06');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (15, 22, 17, 'Et eum nisi alias minima consectetur a.', 'Quibusdam aut aut ea praesentium. Vel sed itaque rem ut est non odit. Ea tempore ipsum tempora harum accusamus ipsum deleniti occaecati.', 15, 0, 1, '1974-11-26 12:10:56', '2012-07-01 06:35:23');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (16, 55, 6, 'Natus quo voluptates doloribus. Aut quia reprehenderit saepe vel.', 'Rerum magni magnam maxime ut placeat eum non. Aspernatur aspernatur dolores itaque ut ad aperiam. Beatae nesciunt officia totam sunt. Quis ab fugit iste pariatur dolor illum debitis eius.', 71, 0, 0, '1978-11-29 20:25:43', '1978-08-21 05:53:12');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (17, 94, 20, 'Totam repellendus quis eum dolorem.', 'Numquam minus est repudiandae architecto facere. Aliquam et expedita fuga magnam. Sint ut consectetur voluptatem quis. Voluptas corrupti aut itaque quam mollitia.', 4, 1, 0, '2006-06-09 16:55:23', '2003-11-26 07:36:47');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (18, 10, 7, 'Exercitationem quos blanditiis aliquam.', 'Sint est quibusdam eligendi. Et consectetur praesentium quasi totam quia quas vel nobis. Ipsam consectetur animi ut qui dicta. Blanditiis dicta quae quibusdam tempore.', 39, 0, 0, '1979-10-21 12:56:23', '2012-08-05 17:06:25');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (19, 96, 13, 'Eaque deleniti quasi praesentium sint.', 'Debitis fuga ad assumenda et et cumque. Earum ut vel animi molestiae. Vel corrupti nihil deserunt in quam minima.', 73, 1, 1, '2009-09-20 13:26:47', '2003-02-05 07:01:39');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (20, 81, 3, 'Optio voluptas sapiente perspiciatis totam voluptas et.', 'Tempore et quod est similique deleniti. Cumque quia fuga aliquam. Inventore quidem minima sit sunt ut porro.\nVeniam qui cupiditate quia ex minus. Dolor consequuntur nemo nobis.', 10, 0, 0, '2012-06-09 18:08:59', '1992-08-19 18:40:51');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (21, 85, 5, 'Quibusdam autem ut sequi aperiam voluptate illum assumenda.', 'Officia vel et sint fugiat ratione repellat. Et consectetur incidunt quasi velit. Est sit necessitatibus saepe expedita sit. Culpa totam placeat qui architecto.', 54, 0, 1, '2001-02-16 07:37:47', '1979-09-21 04:14:04');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (22, 90, 10, 'Quia quae officiis delectus delectus.', 'Et dolorem distinctio et non possimus porro dolores. Eos perspiciatis consequuntur et temporibus sit qui.', 1, 1, 1, '2018-05-05 07:37:17', '1991-02-20 03:10:19');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (23, 68, 10, 'Enim eius quod vel velit necessitatibus.', 'Dignissimos voluptas omnis ducimus in dolorem veritatis recusandae. Harum earum repudiandae dignissimos quibusdam culpa. Molestiae ratione quis architecto molestiae.', 16, 1, 1, '1979-10-14 18:07:51', '1992-03-03 06:09:12');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (24, 88, 15, 'Non quam at iure in ut.', 'Et aut doloribus dignissimos quia est non cumque. Laborum ad ab impedit dolor quod. Ea qui mollitia quia tenetur.', 48, 1, 0, '1979-04-26 09:13:11', '2005-04-17 06:20:34');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (25, 59, 10, 'Impedit et ullam sit delectus. Quae ipsum porro praesentium est.', 'Aut impedit debitis sequi possimus rem eius. Nobis nesciunt voluptas corrupti qui vel aliquid dolorum. In repellat saepe nihil iste est consectetur dolores.', 10, 0, 0, '2007-10-15 08:20:46', '1972-08-05 03:55:35');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (26, 17, 17, 'Similique perferendis in molestias dolores optio.', 'Veritatis saepe et doloribus cupiditate. Rerum consectetur et asperiores sed eligendi itaque. Debitis qui voluptatibus voluptatem magni non fugiat.', 23, 1, 1, '1997-04-14 20:44:28', '1992-03-30 04:02:35');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (27, 6, 16, 'Illum et mollitia officia harum ipsam quo eum.', 'Dolor neque quia quo minima. Magni maiores cumque et officiis consequatur. Ut omnis architecto temporibus nemo. Pariatur tempora voluptas eaque voluptas animi nulla laboriosam.', 37, 0, 0, '1983-09-26 09:45:42', '2019-09-25 14:00:40');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (28, 80, 6, 'Aut sed unde consequatur nobis molestiae.', 'Accusamus a est esse rem vero quis est. Consectetur amet et consequatur non ipsam optio.', 50, 1, 0, '2017-05-17 05:50:47', '2008-02-23 01:18:56');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (29, 50, 9, 'Ipsum ratione quibusdam veniam autem dolores.', 'Architecto velit fuga repellat ut velit. Quo iusto quo impedit sapiente laborum. Iusto perspiciatis dolor non aliquid.', 70, 0, 0, '2000-05-18 07:54:06', '1974-12-27 18:11:12');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (30, 98, 17, 'Eius corporis cumque minus.', 'Soluta perspiciatis qui quaerat voluptatum quia. Iusto omnis sequi natus quia voluptatum pariatur expedita. Sit aut unde quia et corporis nisi ipsum non.', 91, 1, 1, '1981-06-08 13:48:35', '1992-06-08 06:08:05');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (31, 54, 19, 'Consequatur minus odit quisquam dolores.', 'Voluptatem iste corrupti quibusdam sint assumenda maiores odit. Velit sed maiores corrupti natus aut perspiciatis. Rem occaecati odit laborum recusandae delectus excepturi.', 70, 0, 1, '2015-02-25 22:39:20', '1974-06-12 23:13:24');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (32, 37, 19, 'Nihil exercitationem ab laborum quaerat qui.', 'Iusto quia laboriosam alias quos quia rerum. Eum quod nostrum sequi vero ut. Fugiat blanditiis deserunt nam omnis facere. Est ut officiis veniam dicta et molestiae dolorem.', 47, 1, 0, '1993-11-04 08:13:12', '1980-07-10 15:21:57');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (33, 54, 10, 'Iste modi et commodi minus atque.', 'Veritatis qui sunt voluptas aperiam fuga modi. Aut a et nesciunt accusamus dolore totam qui aliquid. Ratione cumque consequatur eaque magni.', 43, 0, 1, '1996-06-20 06:49:10', '2000-11-06 00:30:52');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (34, 36, 2, 'Placeat minus amet impedit enim.', 'Rem aut ratione optio harum enim repellendus. Sed sit ullam minima consequatur optio dolor aut. Debitis magni dignissimos sequi enim voluptatem maiores. Laudantium aliquid delectus et dolores omnis.', 11, 0, 0, '1996-11-19 10:55:03', '1999-04-30 06:30:57');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (35, 53, 5, 'Molestias sequi quos tempora quia nulla.', 'Commodi soluta illum reprehenderit ut quis dolore aliquam fugiat. Maiores iusto beatae laudantium voluptas. Molestiae nobis non velit adipisci voluptas. Dolores et laudantium nostrum exercitationem.', 68, 1, 1, '1992-11-15 12:31:13', '1976-04-11 21:41:14');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (36, 25, 20, 'Quis omnis cumque ut.', 'Veniam quia placeat nesciunt perferendis et impedit laudantium. Vitae ipsum itaque excepturi corporis error quo. Illo sit voluptas qui sed.', 67, 0, 1, '1996-01-20 11:14:56', '2017-11-29 16:42:51');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (37, 78, 9, 'Quae veniam magnam eligendi occaecati consequatur.', 'Est voluptas quisquam recusandae odit sit dolor. Amet quia sunt aut cupiditate nisi dicta similique maiores. Vero ut qui saepe hic modi excepturi incidunt.', 21, 0, 0, '1970-02-09 22:11:18', '2004-07-23 20:33:57');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (38, 89, 3, 'Est quam porro sapiente quae.', 'Aliquam minus sapiente omnis totam explicabo dignissimos. A temporibus laudantium pariatur a quo cum. Illum eligendi reiciendis fugiat harum.', 19, 1, 0, '1983-05-27 18:02:58', '2009-08-28 04:31:25');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (39, 34, 7, 'Quia id porro neque deleniti tempore.', 'Corrupti distinctio consectetur sed et sed id corporis. Fuga et dolore atque voluptate sunt dicta.', 40, 1, 1, '2010-01-08 23:47:49', '2008-04-16 02:46:43');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (40, 16, 2, 'Ut enim necessitatibus qui qui deserunt quo aut et.', 'Rerum unde ea quia est exercitationem. Porro et et non sit ut. Atque est delectus maxime quo quo aliquam amet. Veniam et eligendi aut consectetur cupiditate.', 73, 0, 1, '2009-09-24 16:16:52', '1987-04-01 13:30:05');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (41, 67, 2, 'Eaque ipsum maiores aspernatur numquam.', 'Autem ut doloribus sint qui et vel sed. Ea sit dolor ut labore et vel. Impedit perspiciatis unde sunt harum dolore. Magni id autem beatae aut.', 43, 1, 0, '2013-02-11 07:03:13', '1970-07-19 00:41:15');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (42, 71, 20, 'Adipisci repellat quis accusamus eos dolorem voluptatem eos.', 'Nesciunt quod nobis vero pariatur asperiores eos magni. Voluptatem eos in qui. Labore animi voluptates harum molestias hic. Placeat provident voluptatem mollitia voluptatem possimus illo.', 10, 0, 1, '1980-04-11 18:02:25', '1976-02-03 01:16:17');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (43, 16, 4, 'Sint placeat tempore alias est et neque accusantium soluta.', 'Eaque necessitatibus fuga dolor autem eos. Qui qui cupiditate delectus nam possimus sunt. Repudiandae dolores consectetur architecto et maiores. Eum omnis sint nisi deserunt porro.', 5, 0, 0, '2015-01-30 22:38:03', '1970-05-26 02:41:49');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (44, 79, 10, 'Odio et debitis et accusamus magni.', 'Corrupti nam dolor porro consequatur dolores velit laudantium. Hic ut quo aut debitis dolores at magni vitae. Vero vitae nisi aut eum. Illo eum molestiae quam veniam.', 100, 0, 1, '2005-11-25 08:26:32', '1981-09-09 06:30:53');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (45, 31, 3, 'Tempore praesentium libero alias dolore.', 'Recusandae aut facere dolorem dolorum aut quibusdam. Dolorem rerum sed aut minima minima cumque nesciunt.', 3, 1, 0, '1976-09-21 04:12:43', '1989-08-19 11:35:14');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (46, 5, 17, 'Voluptates non voluptas dolor.', 'Et rerum est quod eos necessitatibus aut. Nobis hic suscipit nisi aperiam consequatur et. Rerum cum sapiente velit voluptates. Praesentium consectetur nesciunt dolor ut illo ea ab.', 99, 0, 1, '2017-07-01 03:59:47', '2018-05-30 12:08:07');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (47, 32, 4, 'Dolores laborum enim eum autem in.', 'Deserunt similique quibusdam illo. Nesciunt accusamus qui quis. Adipisci quas et in ut culpa dolor.', 12, 0, 0, '1973-12-18 13:55:20', '2010-11-01 19:58:50');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (48, 34, 20, 'Occaecati voluptatibus quia dolorem porro quod quo in dolore.', 'Qui cum consequatur exercitationem error et quo. Repellat repellendus fuga vitae est. Cumque excepturi et non. Soluta aut enim esse porro.', 86, 1, 1, '1996-03-01 14:50:45', '2003-10-16 07:56:49');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (49, 11, 14, 'Dolores laborum hic autem provident.', 'Incidunt amet aut quibusdam qui id porro. Excepturi rem ut dolore consequatur mollitia earum expedita. Qui harum dignissimos nihil.', 46, 0, 1, '2020-04-22 05:20:43', '2003-12-07 14:40:58');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (50, 74, 5, 'Exercitationem at dolorem iusto non aliquam incidunt.', 'Natus ut odio commodi. Consequatur omnis nostrum vitae recusandae cum.', 25, 0, 0, '2019-03-03 02:45:24', '1992-07-18 07:22:55');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (51, 45, 4, 'Delectus consequatur labore autem id voluptatem perferendis.', 'Est deserunt quos quae non. Qui sunt sed dolor sequi aut aut. Qui vitae distinctio possimus repellat fugiat. Facere nesciunt aut aut nisi ut earum.', 49, 0, 1, '1973-08-09 05:01:44', '1990-04-01 00:38:32');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (52, 49, 1, 'Itaque et non aut cupiditate.', 'Est eum aspernatur aspernatur sequi maxime. Et reprehenderit occaecati ut eveniet facilis accusamus. Rerum iste et voluptatibus. Rem ea recusandae voluptas nemo quis similique.', 75, 1, 1, '2012-01-04 00:54:05', '1993-06-19 01:30:46');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (53, 30, 10, 'Error et ut eaque unde.', 'Rerum voluptate in et aut. Iste culpa nam qui laboriosam corporis consequuntur.\nAnimi ullam repellat eius aut. Qui optio nam nihil dolorum. Eos dolores assumenda at et nesciunt eius necessitatibus.', 15, 1, 0, '2003-01-11 08:21:04', '2002-05-18 09:43:31');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (54, 99, 14, 'Et est autem ut eius non.', 'Aspernatur excepturi laborum quae modi voluptatum est. Distinctio et facilis aut corrupti amet vero commodi et. Deserunt id aut voluptates excepturi eum. Non fuga sed in voluptatibus iusto a quo.', 67, 1, 1, '2000-05-05 19:15:25', '1993-08-04 02:40:25');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (55, 3, 10, 'Et aut assumenda et dolores explicabo dolorem perspiciatis.', 'Est porro est harum id. Nostrum sint rerum dolorum. Voluptates ut qui recusandae itaque autem. Autem culpa et vitae in distinctio incidunt eligendi.', 98, 1, 0, '1992-06-02 09:36:23', '2010-03-22 07:47:04');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (56, 64, 19, 'Nemo quia optio ducimus voluptas reiciendis laudantium.', 'Esse ut nemo sit. Sint aliquam voluptates ut vitae. Autem aut voluptatem vitae velit placeat rerum inventore.', 4, 1, 0, '1985-02-01 21:29:26', '1970-03-02 07:17:35');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (57, 97, 14, 'Culpa rerum quis modi reiciendis non distinctio ut.', 'Aliquam magnam id qui eligendi cumque impedit est. Voluptatum sit voluptatum et deserunt. Et accusamus voluptas ad nihil aspernatur in.', 32, 1, 1, '1970-01-23 09:09:25', '1982-05-08 18:16:25');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (58, 34, 7, 'Dolor dolorem expedita ut.', 'Itaque voluptas odit rerum voluptas sed eum. Et blanditiis ea quo consequatur veniam nesciunt. Qui sint amet itaque autem qui mollitia. Facere itaque et omnis eum.', 22, 1, 0, '1972-05-10 04:51:06', '1981-12-04 18:03:38');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (59, 7, 19, 'Necessitatibus tenetur culpa quo sunt.', 'Perspiciatis minus velit molestias voluptatem est et. Assumenda reprehenderit quis itaque qui aut asperiores. Deserunt repellat officiis at aperiam perferendis.', 81, 0, 0, '2003-08-31 15:05:03', '1995-10-30 17:48:03');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (60, 3, 10, 'Eos aliquam et pariatur. Quas et dolore ut aut laboriosam.', 'Velit odio rerum soluta est quasi. Sit dolorum fugit in porro quae omnis. Est in doloremque libero officiis ducimus.', 52, 0, 0, '2011-06-21 10:10:04', '2017-11-18 20:14:17');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (61, 40, 8, 'A incidunt modi consequuntur laboriosam in nostrum nulla.', 'Alias sit placeat omnis rerum at. Autem aliquam enim eligendi quae. Aut facilis sapiente provident itaque adipisci. Ut explicabo suscipit minus dolores.', 45, 0, 1, '1986-06-15 01:04:10', '2006-03-30 05:12:02');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (62, 94, 12, 'In qui cumque ipsa voluptate dolor magnam voluptas nesciunt.', 'Reiciendis vel excepturi nobis natus quis fugit. Mollitia eos voluptas sunt et fugiat sapiente. Deleniti reiciendis voluptatum ad in.', 23, 1, 0, '1989-05-11 19:56:53', '1975-11-06 14:50:22');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (63, 87, 19, 'Qui aut ad qui odit minima eum odio.', 'Placeat voluptate repudiandae rem. Qui autem voluptatem est voluptas voluptatem quia tenetur libero. Debitis animi fugiat unde aliquam. Id corrupti optio ipsam porro dicta ipsa vitae.', 95, 1, 0, '2014-10-06 13:24:04', '1972-07-06 13:42:13');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (64, 39, 15, 'Sed molestiae est non et autem.', 'Unde minus sint a vel. Iusto eos tenetur unde adipisci occaecati consectetur. Rerum unde laborum nihil unde.', 58, 1, 0, '2004-12-07 08:22:58', '2015-06-18 04:20:43');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (65, 32, 7, 'Officia ratione qui odit iste.', 'Pariatur est rerum incidunt sit. A et aut non. Ullam sint voluptas aut nam. Laborum qui temporibus dolores exercitationem quisquam adipisci deserunt. Non odio totam consequatur.', 34, 1, 1, '1992-01-17 18:19:45', '1971-03-26 11:23:22');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (66, 34, 2, 'Fugiat impedit quo aut corporis quis quidem.', 'Necessitatibus cupiditate sequi minus dolorum facilis. Et alias ipsa voluptatibus. Natus qui quia vitae recusandae quis amet qui possimus.', 6, 1, 1, '2008-08-10 02:59:24', '1979-09-10 15:33:03');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (67, 74, 6, 'Ratione dicta repudiandae nihil.', 'Corporis qui eos asperiores et molestias quis et. Velit autem ipsa et veniam et sit doloremque. Et error id earum ut provident voluptatem eum.', 9, 0, 0, '1999-05-20 09:46:29', '1988-11-30 19:01:28');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (68, 66, 15, 'Nihil quasi earum consequatur in dolorem quis deserunt quaerat.', 'Eius cumque ut fuga. Explicabo saepe dolore pariatur.', 38, 0, 1, '2001-07-31 14:21:51', '2019-04-07 10:29:21');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (69, 79, 2, 'Qui deserunt accusantium vero expedita.', 'Deleniti sapiente deleniti sed. Quidem optio labore quis laboriosam voluptatem et voluptate. Aut animi hic eos magnam tempora impedit.', 28, 0, 0, '1975-05-12 09:31:57', '1986-01-05 06:14:53');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (70, 84, 10, 'Qui voluptates dolor dolor labore explicabo quia est porro.', 'Quasi dicta porro eligendi et a aut expedita. Laborum quia voluptatem enim aspernatur repudiandae doloremque aut. Voluptas earum ut ut ea dolore et. Et aut vel natus ut voluptates consequatur.', 56, 0, 1, '1987-04-30 03:29:51', '2001-05-10 01:34:46');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (71, 12, 7, 'Explicabo consequatur sunt et. Exercitationem quo minus dolorem est.', 'Dolor aliquam nemo repellat ipsam hic. Maxime cupiditate dolor eum quam nam perspiciatis itaque. Vero sint nihil est sit non delectus ipsam. Quos tempora cumque enim asperiores voluptas.', 18, 1, 0, '1984-12-05 01:45:16', '2005-05-27 23:31:04');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (72, 36, 20, 'Cumque aut deserunt incidunt dicta error neque repellat.', 'Molestiae magni a id facere eveniet aliquid facilis. Soluta nobis esse velit omnis possimus excepturi. Laudantium placeat facilis consequatur dolorem non.', 28, 0, 1, '1984-08-19 13:51:13', '2005-07-23 10:47:20');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (73, 80, 19, 'Laboriosam labore architecto consequatur dolor.', 'Molestiae nesciunt ut rem reprehenderit beatae. Rerum et dicta cumque qui aperiam eaque. Quisquam laboriosam odio velit qui. Nostrum alias pariatur nesciunt fuga vel enim laboriosam.', 97, 1, 0, '2010-04-30 22:24:45', '1975-01-13 08:15:33');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (74, 64, 10, 'Consequatur aut sunt explicabo nesciunt.', 'Soluta natus optio numquam quisquam ut. Reprehenderit optio veritatis aut dolores ipsa. Eum cupiditate beatae maxime qui. Voluptas sint fugiat hic in voluptates mollitia consequatur similique.', 41, 1, 0, '1971-06-23 03:13:37', '2016-09-07 02:10:58');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (75, 40, 6, 'Quos sunt voluptatem quae est voluptates et consequatur.', 'Quo aut ut iure tempora ut quod. Sed et sunt saepe laudantium laborum rerum sunt. Delectus incidunt aperiam voluptatem voluptas et et et a.', 29, 0, 0, '1999-11-03 15:22:17', '1980-01-15 00:41:41');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (76, 2, 12, 'Itaque soluta aut officiis porro.', 'Maiores in quasi harum quaerat iste modi id voluptatem. Ea quibusdam eum neque eius omnis optio iste. Dolores debitis deserunt occaecati et.', 42, 1, 0, '2017-02-08 21:12:05', '1997-07-25 16:11:19');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (77, 36, 15, 'Quis quo qui itaque mollitia doloribus quisquam repudiandae et.', 'Quis dolor saepe quos eveniet ea incidunt. Repellat velit a esse fugit quaerat iste. Necessitatibus velit consequuntur beatae ea.', 28, 0, 0, '2011-03-12 18:53:04', '1975-08-27 13:20:50');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (78, 36, 19, 'Officia itaque ratione amet quasi iste quo.', 'Qui sed hic quisquam sunt placeat pariatur. Consequatur veritatis reprehenderit omnis et quasi earum cumque ab. Harum natus quaerat vero ea.', 44, 1, 0, '2011-04-07 03:57:57', '2010-09-17 22:58:48');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (79, 47, 19, 'Voluptatem incidunt ab eos labore velit magni accusamus.', 'Deleniti quaerat pariatur sunt. Sit aut deleniti ipsum minima. Eligendi quas dolor voluptatem optio nihil.', 86, 1, 1, '1974-11-09 03:38:40', '1971-11-16 09:43:32');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (80, 31, 1, 'Et dicta qui ipsam et dolor labore. Dolorum ratione optio animi.', 'Officia voluptate dolorem numquam placeat architecto vel. Quos asperiores facilis sit rerum sint possimus. Asperiores ipsum omnis provident labore. Laborum ipsum ab iusto deserunt eos.', 34, 1, 1, '1982-05-08 07:57:15', '2008-06-19 00:12:52');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (81, 39, 17, 'Possimus quibusdam et eum modi maiores earum omnis.', 'Id omnis omnis qui ut eum dolor expedita. Et dolor quam tempora. Tenetur veniam placeat reiciendis.', 92, 1, 1, '2012-05-21 00:55:21', '2020-02-28 15:26:45');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (82, 1, 19, 'Reiciendis temporibus omnis earum sed.', 'Autem magnam ut cumque nobis. Sed beatae iusto a aspernatur. Rerum accusamus ut hic omnis libero. Sed eos corporis at dolor voluptatibus iste quia.', 21, 0, 0, '1985-02-22 18:50:39', '2002-05-30 11:28:28');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (83, 13, 17, 'Alias quis velit corporis in adipisci eveniet.', 'Quas sunt non consequatur et error perferendis. Consectetur consectetur eum excepturi voluptate sed. Ut ut dicta facere.', 41, 1, 1, '2015-07-18 04:16:46', '1995-07-02 17:55:27');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (84, 30, 9, 'Ex est voluptatibus eum voluptates.', 'Est excepturi delectus consequuntur. Mollitia vel et aut sit ipsam incidunt ad. Sed qui minima qui eos rerum placeat. Voluptas qui aspernatur odio quaerat dolorem minima magnam.', 71, 0, 0, '1989-04-21 09:15:03', '2011-04-30 07:11:16');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (85, 30, 9, 'Aperiam modi omnis veniam optio tenetur.', 'Quia et excepturi voluptatem est. Nesciunt quis tempore magnam iusto ut. In omnis dolores libero non. Quidem similique eos voluptatem pariatur a ab facere. Incidunt cum ut id.', 90, 0, 1, '2014-11-03 15:12:01', '2004-12-24 23:10:19');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (86, 19, 17, 'Ab in magnam voluptatibus.', 'Illum voluptatibus earum eos consectetur accusantium. Exercitationem nisi magni et modi omnis velit. Dolor id quia repellat deserunt a in sapiente.', 39, 1, 1, '2012-12-03 11:33:51', '1995-04-04 19:52:00');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (87, 55, 15, 'Est delectus in architecto. Dolor quia id omnis voluptatem.', 'Nulla minima suscipit debitis unde natus maxime quis. Nulla quia nemo cupiditate totam. Dolorum sint et qui et consequatur veniam voluptas enim. Minus mollitia impedit itaque aut dicta.', 32, 1, 1, '2009-06-25 08:35:47', '2011-07-10 21:19:32');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (88, 77, 17, 'Inventore perferendis beatae perspiciatis modi ullam molestiae.', 'Beatae et iure rerum maiores qui ex ut. Blanditiis officiis quasi et distinctio earum. Soluta nisi voluptas odio sunt vero omnis quo. Accusamus quod distinctio fugit earum.', 67, 0, 1, '1985-04-23 20:31:52', '1976-09-13 13:41:13');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (89, 49, 1, 'Labore nihil voluptatem et est omnis quis eligendi qui.', 'Numquam aut non consequatur sit. Eveniet laborum ad ex eum laboriosam reiciendis. Voluptatem voluptatem et voluptatem voluptates consequuntur ducimus.', 6, 0, 0, '1990-06-15 05:10:41', '2004-07-13 00:17:21');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (90, 99, 2, 'Consequuntur ex aut a impedit.', 'Et dolorem illum eum labore voluptates officia. Magnam facilis quos aspernatur rerum id totam. Porro inventore eveniet dolorum dolores. Neque architecto facere repudiandae eius id est voluptatem et.', 19, 0, 1, '1984-05-11 15:46:26', '2005-03-29 15:04:01');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (91, 58, 5, 'Rerum provident recusandae qui minima.', 'Voluptatem ipsam ea ea rerum ratione molestiae. Voluptatibus ex provident commodi quis aut molestiae. Reiciendis ipsum facilis eveniet. Incidunt corporis exercitationem itaque nostrum aut earum.', 58, 0, 1, '1982-05-26 18:07:25', '2014-09-01 01:23:58');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (92, 71, 4, 'Unde et ea vero aut quidem aut.', 'Quia laboriosam tempora et repellat. Incidunt fuga eligendi beatae qui. Et suscipit inventore voluptas nostrum inventore dolores eligendi.', 48, 1, 1, '2004-07-07 16:25:15', '2000-04-22 09:42:26');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (93, 93, 6, 'Delectus quisquam ad quam.', 'Quo qui quo temporibus beatae. Omnis sequi aliquam qui saepe. Nemo dolor fugit illum nulla soluta sint.', 34, 0, 0, '2000-04-11 22:48:01', '2009-05-06 21:34:10');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (94, 24, 12, 'Quae delectus maiores et qui.', 'Distinctio optio quisquam hic aut iusto provident enim. Id officia minus voluptas nobis enim cupiditate facere vitae.', 33, 1, 0, '1973-03-04 19:24:06', '1985-05-25 06:57:07');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (95, 18, 11, 'Magnam aut deserunt aut voluptatem.', 'Dolores est quo vel eum aliquid temporibus. Corporis maxime quo dicta occaecati.', 47, 1, 1, '1989-05-25 17:10:45', '2001-10-25 11:29:59');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (96, 53, 11, 'Illum totam consectetur quasi sed.', 'Voluptas dolorem minima possimus sapiente qui est est. Totam ea veniam ipsa qui error. Deserunt enim veritatis itaque consequuntur.', 3, 0, 0, '1983-07-13 08:36:54', '2011-09-07 21:42:33');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (97, 29, 9, 'Dicta qui ad enim excepturi aperiam occaecati. Aut ex aut nobis nemo.', 'Aut unde quod doloribus vel quasi earum voluptatem. Est nisi excepturi adipisci sequi. Harum esse nesciunt blanditiis minima sit ipsam.', 66, 1, 0, '1974-04-23 11:46:45', '1976-05-10 09:07:18');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (98, 45, 19, 'Aut architecto adipisci autem quidem. Eius alias qui mollitia.', 'Nobis nam asperiores qui aut et tempora corporis pariatur. Et est amet odit occaecati qui blanditiis tempore. Sequi vel omnis sequi nihil et aspernatur ut.', 87, 0, 0, '2012-07-14 11:32:08', '1971-03-20 04:43:25');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (99, 23, 8, 'Qui labore aut placeat sed.', 'Dolor veniam non dolores praesentium et sunt mollitia corporis. Similique voluptas cupiditate aliquam repellendus occaecati. Et error fuga aut amet est molestiae.', 56, 0, 0, '1992-12-31 17:27:58', '1999-05-22 01:16:26');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (100, 40, 10, 'Sit et et sunt vero dolores nam magni rerum.', 'Non eos quis soluta est non mollitia soluta. Et impedit eligendi consequatur facilis. Quidem dolores quos saepe id quasi beatae voluptatem.', 78, 0, 0, '1984-02-25 14:53:36', '1976-07-18 18:06:29');


